FROM ubuntu:22.04

ENV FLUTTER_HOME=${HOME}/sdks/flutter \
    FLUTTER_VERSION=3.22.0
ENV FLUTTER_ROOT=$FLUTTER_HOME

ENV PATH ${PATH}:${FLUTTER_HOME}/bin:${FLUTTER_HOME}/bin/cache/dart-sdk/bin

RUN apt update
RUN apt install -y --no-install-recommends curl ca-certificates git unzip cmake make ninja-build clang pkg-config libgtk-3-dev libssl-dev


# install flutter
RUN git clone --depth 1 --branch ${FLUTTER_VERSION} https://github.com/flutter/flutter.git ${FLUTTER_HOME}

RUN flutter channel

RUN flutter doctor \
    && chown -R root:root ${FLUTTER_HOME} \
    && flutter config --enable-linux-desktop \
    && flutter precache --linux

RUN apt remove -y curl unzip
RUN apt autorem